AnimeList/Models/Anime.cs
using AnimeList.Data.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AnimeList.Models
{
    public class Anime
    {
        [Key]
        public int Id { get; set; }

        public string? ImageUrl { get; set; }

        public string? Title { get; set; }

        public string? Synopsis { get; set; }

        public string? Genre { get; set; }

        public string? Status { get; set; }

        public DateTime? ReleaseDate { get; set; }

        public AnimeFormat? Format { get; set; }

        public double? Price { get; set; }

        public string? TrailerUrl { get; set; }

        // Relationships
        public List<Anime_VoiceActor>? Animes_VoiceActors { get; set; }

        public int StudioId { get; set; }
        [ForeignKey("StudioId")]
        public Studio? Studio { get; set; }

        public int ProducerId { get; set; }
        [ForeignKey("ProducerId")]
        public Producer? Producer { get; set; }
    }
}

AnimeList/Models/Anime_VoiceActor.cs
namespace AnimeList.Models
{
    public class Anime_VoiceActor
    {
        public int AnimeId { get; set; }
        public Anime? Anime { get; set; }

        public int VoiceActorId { get; set; }
        public VoiceActor? VoiceActor { get; set; }
    }
}

AnimeList/Models/ErrorViewModel.cs
namespace AnimeList.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AnimeList/Models/Producer.cs
using System.ComponentModel.DataAnnotations;

namespace AnimeList.Models
{
    public class Producer
    {
        [Key]
        public int Id { get; set; }

        public string? ImageUrl { get; set; }

        public string? Name { get; set; }

        public List<Anime>? Animes { get; set; }
    }
}

AnimeList/Models/Studio.cs
using System.ComponentModel.DataAnnotations;

namespace AnimeList.Models
{
    public class Studio
    {
        [Key]
        public int Id { get; set; }

        public string? ImageUrl { get; set; }

        public string? Name { get; set; }

        public List<Anime>? Animes { get; set; }
    }
}

AnimeList/Models/VoiceActor.cs
using System.ComponentModel.DataAnnotations;

namespace AnimeList.Models
{
    public class VoiceActor
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "This is required.")]
        public string? ImageUrl { get; set; }

        [Required(ErrorMessage = "This is required.")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "This is required.")]
        public string? Language { get; set; }

        public List<Anime_VoiceActor>? Animes_VoiceActors { get; set; }
    }
}

AnimeList/Controllers/AnimesController.cs
using AnimeList.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AnimeList.Controllers
{
    public class AnimesController : Controller
    {
        private readonly AppDbContext _context;

        public AnimesController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _context.Animes.Include(a => a.Studio).ToListAsync();
            return View(data);
        }
    }
}

AnimeList/Controllers/ProducersController.cs
using AnimeList.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AnimeList.Controllers
{
    public class ProducersController : Controller
    {
        private readonly AppDbContext _context;

        public ProducersController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _context.Producers.ToListAsync();
            return View(data);
        }
    }
}

AnimeList/Controllers/StudiosController.cs
using AnimeList.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AnimeList.Controllers
{
    public class StudiosController : Controller
    {
        private readonly AppDbContext _context;

        public StudiosController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _context.Studios.ToListAsync();
            return View(data);
        }
    }
}

AnimeList/Controllers/VoiceActorsController.cs
using AnimeList.Data.Services;
using AnimeList.Models;
using Microsoft.AspNetCore.Mvc;

namespace AnimeList.Controllers
{
    public class VoiceActorsController : Controller
    {
        private readonly IVoiceActorsService _service;

        public VoiceActorsController(IVoiceActorsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(VoiceActor voiceActor)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(voiceActor);
                return RedirectToAction(nameof(Index));
            }

            return View(voiceActor);
        }

        public async Task<IActionResult> Details(int id)
        {
            var voiceActor = await _service.GetByIdAsync(id);

            if (voiceActor is null)
            {
                return View(nameof(NotFound));
            }

            return View(voiceActor);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var voiceActor = await _service.GetByIdAsync(id);
            return View(voiceActor);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VoiceActor voiceActor)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateAsync(voiceActor);
                return RedirectToAction(nameof(Details), new { id = voiceActor.Id });
            }

            return View(voiceActor);
        }

        public async Task<IActionResult> Delete(int id)
        {
			await _service.DeleteAsync(id);
			return RedirectToAction(nameof(Index));
		}
    }
}

AnimeList/Views/Animes/Index.cshtml
@model IEnumerable<Anime>

@{
    ViewBag.Title = "Animes";
}

<div class="row">
    @foreach (var anime in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @anime.Title
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@anime.ImageUrl" style="height: 100%; max-width:100%" alt="@anime.Title">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@anime.Synopsis</p>
                            <p class="card-text"><b>Studio: </b>@anime.Studio?.Name</p>
                            <p class="card-text"><b>Format: </b>@anime.Format</p>
                            <p class="card-text"><b>Release Date: </b>@anime.ReleaseDate?.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>Genre: </b>@anime.Genre</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= anime.ReleaseDate)
                                {
                                    <span class="badge bg-success text-white">AIRING</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-success text-white float-end">
                                    <i class="bi bi-cart-plus"></i> Add to Cart (@anime.Price?.ToString("c"))
                                </a>

                                <a class="btn btn-outline-primary float-right">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

AnimeList/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AnimeList/Views/Producers/Index.cshtml
@model IEnumerable<Producer>

@{
	ViewBag.Title = "Producers";
}

<div class="row">
	<div class="col-md-8 offset-md-2">
		<table class="table">
			<thead>
				<tr>
					<th>Picture</th>
					<th>Name</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var producers in Model)
				{
					<tr>
						<td class="align-middle">
							<img class="rounded" style="height: 200px" src="@producers.ImageUrl" alt="@producers.Name" />
						</td>
						<td class="align-middle">
							@producers.Name
						</td>
						<td class="align-middle">
							<a class="btn btn-outline-primary mx-1 h-100"><i class="bi bi-pencil-square pe-2"></i>Edit</a>
							<a class="btn btn-outline-info mx-1 h-100"><i class="bi bi-eye pe-2"></i>Details</a>
							<a class="btn btn-danger mx-1 h-100"><i class="bi bi-trash pe-2"></i>Delete</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

AnimeList/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Animes" asp-action="Index">Home Page</a>
    </div>
</div>

AnimeList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - AnimeList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Animes" asp-action="Index">AnimeList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animes" asp-action="Index"><i class="bi bi-film"></i> Animes</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> Management
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Studios" asp-action="Index"><i class="bi bi-camera-reels"></i> Studios</a>
                                <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                <a class="dropdown-item" asp-controller="VoiceActors" asp-action="Index"><i class="bi bi-person-square"></i> Voice Actors</a>
                            </div>
                        </li>
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Animes" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - eTickets
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AnimeList/Views/Studios/Index.cshtml
@model IEnumerable<Studio>

@{
	ViewBag.Title = "Studios";
}

<div class="row">
	<div class="col-md-8 offset-md-2">
		<table class="table">
			<thead>
				<tr>
					<th>Picture</th>
					<th>Name</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var voiceActor in Model)
				{
					<tr>
						<td class="align-middle">
							<img class="rounded" style="height: 200px" src="@voiceActor.ImageUrl" alt="@voiceActor.Name" />
						</td>
						<td class="align-middle">
							@voiceActor.Name
						</td>
						<td class="align-middle">
							<a class="btn btn-outline-primary mx-1 h-100"><i class="bi bi-pencil-square pe-2"></i>Edit</a>
							<a class="btn btn-outline-info mx-1 h-100"><i class="bi bi-eye pe-2"></i>Details</a>
							<a class="btn btn-danger mx-1 h-100"><i class="bi bi-trash pe-2"></i>Delete</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

AnimeList/Views/VoiceActors/Create.cshtml
@model VoiceActor

@{
    ViewBag.Title = "Add Voice Actor";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <div class="text-center">
            <h3>Add a New Voice Actor</h3>
        </div>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" class="border-info rounded" style="max-width: 150px" />
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="ImageUrl" class="control-label mb-2">Image Url</label>
                        <input asp-for="ImageUrl" class="form-control" />
                        <span asp-validation-for="ImageUrl" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="Name" class="control-label mb-2">Name</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="Language" class="control-label mb-2">Language</label>
                        <input asp-for="Language" class="form-control" />
                        <span asp-validation-for="Language" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <a class="btn btn-outline-secondary mt-2 float-right" asp-action="Index">Go Back</a>
                        <input type="submit" value="Create" class="btn btn-outline-success float-end me-2 mt-2" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ImageUrl").val();
        })

        $("#ImageUrl").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

AnimeList/Views/VoiceActors/Details.cshtml
@model VoiceActor

@{
    ViewBag.Title = Model.Name + " Details";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <div class="text-center">
            <h3>Details for @Model.Name</h3>
        </div>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group text-center">
                    <img class="border-info rounded" style="max-width: 150px" id="ProfilePicturePreview" />
                </div>
                <div class="form-group mb-2">
                    <label asp-for="ImageUrl" class="control-label mb-2">Image Url</label>
                    <input asp-for="ImageUrl" class="form-control" readonly />
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="form-group mb-2">
                    <label asp-for="Name" class="control-label mb-2">Name</label>
                    <input asp-for="Name" class="form-control" readonly />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group mb-2">
                    <label asp-for="Language" class="control-label mb-2">Language</label>
                    <input asp-for="Language" class="form-control" readonly />
                    <span asp-validation-for="Language" class="text-danger"></span>
                </div>

                <div class="form-group mt-2">
                    <a class="btn btn-outline-secondary mt-2 float-right" asp-action="Index">Go Back</a>
                    <a class="btn btn-outline-success float-end me-2 mt-2" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ImageUrl").val();
        })
    </script>
}

AnimeList/Views/VoiceActors/Edit.cshtml
@model VoiceActor

@{
    ViewBag.Title = "Edit " + Model.Name;
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <div class="text-center">
            <h3>Edit @Model.Name</h3>
        </div>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" class="border-info rounded" style="max-width: 150px" />
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="ImageUrl" class="control-label mb-2">Image Url</label>
                        <input asp-for="ImageUrl" class="form-control" />
                        <span asp-validation-for="ImageUrl" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="Name" class="control-label mb-2">Name</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="Language" class="control-label mb-2">Language</label>
                        <input asp-for="Language" class="form-control" />
                        <span asp-validation-for="Language" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <a class="btn btn-outline-danger mt-2 float-right" onclick="history.back()">Cancel</a>
                        <input type="submit" value="Update" class="btn btn-outline-success float-end me-2 mt-2" asp-route-id="@Model.Id" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ImageUrl").val();
        })

        $("#ImageUrl").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

AnimeList/Views/VoiceActors/Index.cshtml
@model IEnumerable<VoiceActor>

@{
	ViewBag.Title = "Voice Actors";
}

<div class="row">
	<div class="col-md-8 offset-md-2">
		<table class="table">
			<thead>
				<tr>
					<th>Picture</th>
					<th>Name</th>
					<th>Language</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var voiceActor in Model)
				{
					<tr>
						<td class="align-middle">
							<img class="rounded" style="height: 200px" src="@voiceActor.ImageUrl" alt="@voiceActor.Name" />
						</td>
						<td class="align-middle">
							@voiceActor.Name
						</td>
						<td class="align-middle">
							@voiceActor.Language
						</td>
						<td class="align-middle">
							<form asp-action="Delete" asp-route-id="@voiceActor.Id" class="mx-1 h-100">
								<a class="btn btn-outline-primary mx-1 h-100" asp-action="Edit" asp-route-id="@voiceActor.Id"><i class="bi bi-pencil-square pe-2"></i>Edit</a>
								<a class="btn btn-outline-info mx-1 h-100" asp-action="Details" asp-route-id="@voiceActor.Id"><i class="bi bi-eye pe-2"></i>Details</a>
								<button type="submit" class="btn btn-danger"><i class="bi bi-trash pe-2"></i>Delete</button
							</form>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

<div class="text-white" style="position:fixed; bottom:25px; right:25px">
	<a asp-controller="VoiceActors" asp-action="Create" class="btn btn-success">
		<i class="bi bi-plus-circle me-2"></i>Add New
	</a>
</div>